feat(icons): update icons from latest icon font
s4hana
translate
feedback
megamenu
text-formatting

detail-view (same as show-edit)
status-completed (same as status-positive)
status-error (same as status-negative)
status-in-process (same as status-critical)
notification (same as message-error)
information (same as message-information)

message-error: exclamation mark replaced by x
error: exclamation mark replaced by x
message-success: square shape replaced by circle
message-information: square shape replaced by circle
question-mark: square shape replaced by circle
locked
unlocked
value-help - style adapted to Fiori3 requirements

car-rental
batch-payments
folder-blank
measurement-document
measuring-point
folder

multiple icons had missing top or bottom pixels due to wrong vertical alignment