fix(framework): copy "base" pkg i18n assets to `dist/prod` (#12072)
Recently added i18n texts to the `base` package are not properly shipped - the i18n assets are missing from `@ui5/webcomponents-base/dist/prod/generated/assets/i18n` folder, causing issues like:

> RollupError: Could not resolve "../assets/i18n/messagebundle_en.json"
> from "node_modules/@ui5/webcomponents-base/dist/prod/generated/json-imports/i18n.js"                                                                              

With this change, the assets are copied and present in dist/prod.